http:
  address: 0.0.0.0:4195
  debug_endpoints: false

input:
  label: ""
  kafka:
    addresses: [localhost:9092]
    topics: [biography]
    consumer_group: "bio enrichment lookup"
    client_id: benthos
    start_from_oldest: true
    checkpoint_limit: 1024
    commit_period: 1s
    max_processing_period: 100ms
    group:
      session_timeout: 10s
      heartbeat_interval: 3s
      rebalance_timeout: 60s
    fetch_buffer_cap: 256

buffer:
  none: {}

output:
  label: ""
  sql_insert:
    driver: "mysql" # No default (required)
    dsn: root:root@tcp(localhost:3306)/Lookup # No default (required)
    table: Biography # No default (required)
    columns: [name, biography] # No default (required)
    args_mapping: root = [meta("kafka_key"), content() ] # No default (required) (hard to understand, use content() for full body)
    max_in_flight: 64
    init_statement: | # No default (optional)
      create table if not exists Lookup.Biography(
        Name varchar(255) not null primary key,
        Biography text null
      );

logger:
  level: INFO
  static_fields:
    '@service': benthos

